version: "3"
services:
    node:
        build:
            context: ../..
            dockerfile: servers/docker/node/Dockerfile
        volumes:
            - ../../src/js:/app
    api:
        build:
            context: ../..
            dockerfile: servers/docker/php/api/Dockerfile
        volumes:
            - ../../src/php:/var/www
    cli_convert:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/convert/Dockerfile
        volumes:
            - ../../src/php:/var/www
    cli_youtube:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/youtube/Dockerfile
        volumes:
            - ../../src/php:/var/www
    cli_vimeo:
        build:
            context: ../..
            dockerfile: servers/docker/php/cli/vimeo/Dockerfile
        volumes:
            - ../../src/php:/var/www
    init:
        build:
            context: ../..
            dockerfile: servers/docker/php/init/Dockerfile
        volumes:
            - ../../src/php:/var/www
    nginx:
        build:
            context: ../..
            dockerfile: servers/docker/nginx/Dockerfile
        volumes:
            - ../../src/php:/var/www
